version: '2.1'
volumes:
  devvenv:
services:
  webapp:
    entrypoint: /bin/bash -c "chmod +x /webodm/*.sh && /bin/bash -c \"/webodm/wait-for-postgres.sh db /webodm/wait-for-it.sh -t 0 broker:6379 -- /webodm/start.sh --create-default-pnode --setup-devenv\""
    ports:
      - "35729:35729"
    environment:
      - WO_SKIP_PLUGIN_REBUILD=YES
      - WO_AGRITRACK_RESULTS_PUSH_URL=${WO_AGRITRACK_RESULTS_PUSH_URL}
      - WO_AGRITRACK_OUTBOUND_API_KEY=${WO_AGRITRACK_OUTBOUND_API_KEY}
    volumes:
      - .:/webodm
      - devvenv:/webodm/venv
  worker:
    environment:
      - WO_SKIP_PLUGIN_REBUILD=YES
      - WO_AGRITRACK_RESULTS_PUSH_URL=${WO_AGRITRACK_RESULTS_PUSH_URL}
      - WO_AGRITRACK_OUTBOUND_API_KEY=${WO_AGRITRACK_OUTBOUND_API_KEY}
    volumes:
      - .:/webodm
      - devvenv:/webodm/venv