# Generated by Django 2.2.27 on 2026-07-05 18:56

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0047_task_wkt'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boundary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Field boundary', max_length=255, verbose_name='Name')),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(help_text='Field boundary polygon (WGS84)', srid=4326, verbose_name='Geometry')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=16, verbose_name='Status')),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_boundaries', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_boundaries', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(help_text='Capture (imported orthophoto task) this boundary belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='boundaries', to='app.Task', verbose_name='Capture')),
            ],
            options={
                'verbose_name': 'Boundary',
                'verbose_name_plural': 'Boundaries',
                'ordering': ['-created_at'],
            },
        ),
    ]
