# Generated by Django 2.2.27 on 2026-07-05 20:52

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0047_task_wkt'),
        ('agri', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisRun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('PENDING_REVIEW', 'Pending review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('FAILED', 'Failed')], default='PENDING', max_length=20, verbose_name='Status')),
                ('index_used', models.CharField(blank=True, default='', help_text='Vegetation index used (e.g. NDVI, ExG)', max_length=32)),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('boundary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_runs', to='agri.Boundary')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_analyses', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_runs', to='app.Task', verbose_name='Capture')),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_analyses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Analysis Run',
                'verbose_name_plural': 'Analysis Runs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('rgb_index', 'RGB Index'), ('plant_health', 'Plant Health'), ('grid', 'Grid Analysis'), ('weed', 'Weed Mapping'), ('canopy', 'Canopy Cover'), ('report', 'Report')], max_length=20, verbose_name='Kind')),
                ('asset_path', models.CharField(blank=True, default='', help_text='Path (relative to the task assets dir) of the result asset', max_length=1024)),
                ('stats', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, verbose_name='Statistics')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='agri.AnalysisRun')),
            ],
            options={
                'verbose_name': 'Analysis Result',
                'verbose_name_plural': 'Analysis Results',
                'ordering': ['kind'],
            },
        ),
    ]
