# Generated by Django 2.2.27 on 2026-07-06 14:48

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0047_task_wkt'),
        ('agri', '0002_analysisresult_analysisrun'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgriFarm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agritrack_farm_id', models.IntegerField(db_index=True, unique=True, verbose_name='AgriTrack Farm ID')),
                ('agritrack_farmer_id', models.IntegerField(blank=True, null=True, verbose_name='AgriTrack Farmer (User) ID')),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('location', models.CharField(blank=True, default='', max_length=255)),
                ('boundary', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326)),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agri_farm', to='app.Project', verbose_name='Farm (Project)')),
            ],
            options={
                'verbose_name': 'AgriTrack Farm',
                'verbose_name_plural': 'AgriTrack Farms',
            },
        ),
        migrations.CreateModel(
            name='AgriField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agritrack_field_id', models.IntegerField(db_index=True, unique=True, verbose_name='AgriTrack Field ID')),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('crop', models.CharField(blank=True, default='', max_length=255)),
                ('area_ha', models.FloatField(blank=True, null=True)),
                ('boundary', django.contrib.gis.db.models.fields.PolygonField(srid=4326, verbose_name='Authoritative Boundary')),
                ('scan_frequency', models.CharField(blank=True, default='', help_text='daily | weekly | manual', max_length=16)),
                ('scan_preferred_time', models.CharField(blank=True, default='', max_length=5)),
                ('scan_enabled', models.BooleanField(default=False)),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='agri.AgriFarm')),
            ],
            options={
                'verbose_name': 'AgriTrack Field',
                'verbose_name_plural': 'AgriTrack Fields',
            },
        ),
        migrations.AddField(
            model_name='boundary',
            name='agri_field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boundaries', to='agri.AgriField', verbose_name='AgriTrack Field'),
        ),
    ]
