# Generated by Django 2.2.27 on 2026-07-06 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0047_task_wkt'),
        ('agri', '0003_auto_20260706_1448'),
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agri_field', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='field', to='agri.AgriField', verbose_name='AgriTrack Field')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agri_fields', to='app.Project', verbose_name='Farm (Project)')),
            ],
            options={
                'verbose_name': 'Field',
                'verbose_name_plural': 'Fields',
                'ordering': ['name'],
                'unique_together': {('project', 'name')},
            },
        ),
        migrations.CreateModel(
            name='CaptureMeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capture_date', models.DateField(help_text='Date the imagery was acquired (flight date)', verbose_name='Capture date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='capture_meta', to='app.Task', verbose_name='Capture')),
            ],
            options={
                'verbose_name': 'Capture Metadata',
                'verbose_name_plural': 'Capture Metadata',
            },
        ),
        migrations.AddField(
            model_name='boundary',
            name='field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boundaries', to='agri.Field', verbose_name='Field'),
        ),
    ]
